add environment variable info to meta data (#191)
Add information about the environment variable changes to be applied when starting a view to the `$mount/meta/env.json` file in the generated image.
* replace the `add-compiler-paths.py` script with `envvars.py`
* the `activate.sh` script is not longer used

Add two new views: `spack` and `modules`.
* the `modules` view replaces the `uenv modules use` command
* these link to `/dev/null`, so that activating them with older versions of uenv is a noop.


Additional fixes:

* support workflows where no Spack repos are provided
    * this was broken, because on Alps there is always at least one external repo.
* add error handling for the initial Spack bootstrap
    * this was not failing if there was an error

diff --git a/stackinator/templates/Makefile b/stackinator/templates/Makefile
--- a/stackinator/templates/Makefile
+++ b/stackinator/templates/Makefile
@@ -29,8 +29,13 @@ spack-setup: spack-version
 		exit 1; \
 	fi; \
 	printf "checking if spack concretizer works... "; \
-	$(SANDBOX) $(SPACK) spec zlib > /dev/null; \
-	printf "yup\n"
+	$(SANDBOX) $(SPACK_HELPER) -d spec zlib > $(BUILD_ROOT)/spack-bootstrap-output 2>&1; \
+	if [ "$$?" != "0" ]; then \
+		printf " failed, see %s\n" $(BUILD_ROOT)/spack-bootstrap-output; \
+		exit 1; \
+	fi; \
+	printf " success\n"; \
+	touch spack-setup
 
 pre-install: spack-setup
 	$(SANDBOX) $(STORE)/pre-install-hook
@@ -55,15 +60,20 @@ environments: compilers
 	$(SANDBOX) $(MAKE) -C $@
 
 modules: environments generate-config
-	$(SANDBOX) $(SPACK) -C $(SOFTWARE_STACK_PROJECT)/modules module tcl refresh --upstream-modules --delete-tree --yes-to-all
+	$(SANDBOX) $(SPACK) -C $(BUILD_ROOT)/modules module tcl refresh --upstream-modules --delete-tree --yes-to-all
 
 post-install: generate-config environments{% if modules %} modules{% endif %}
 
+	{% if post_install_hook %}
 	$(SANDBOX) $(STORE)/post-install-hook
+	{% endif %}
+	touch post-install
+
+$(BUILD_ROOT)/store/meta/env.json: post-install
+	$(SANDBOX) $(BUILD_ROOT)/envvars.py uenv {% if modules %}--modules{% endif %} --spack={{ spack_meta.url }},{{ spack_meta.commit }} $(STORE)
 
 # Create a squashfs file from the installed software.
-store.squashfs: environments generate-config{% if modules %} modules{% endif %}{% if post_install_hook %} post-install{% endif %}
-
+store.squashfs: $(BUILD_ROOT)/store/meta/env.json
 	# clean up the __pycache__ paths in the repo
 	$(SANDBOX) find $(STORE)/repo -type d -name __pycache__ -exec rm -r {} +
 	$(SANDBOX) env -u SOURCE_DATE_EPOCH "$$($(SANDBOX) $(SPACK_HELPER) -e ./compilers/bootstrap find --format='{prefix}' squashfs | head -n1)/bin/mksquashfs" $(STORE) $@ -all-root -all-time $$(date +%s) -no-recovery -noappend -Xcompression-level 3
